# Generated by Django 4.2.2 on 2023-07-03 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(blank=True, max_length=8, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('diner', 'diner'), ('snacks', 'snacks')], max_length=40, null=True)),
                ('carbohydrate', models.CharField(blank=True, choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('very high', 'very high')], max_length=150, null=True)),
                ('fats', models.CharField(blank=True, choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('very high', 'very high')], max_length=150, null=True)),
                ('protein', models.CharField(blank=True, choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('very high', 'very high')], max_length=150, null=True)),
                ('calorie', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('unit', models.CharField(blank=True, choices=[('saucer', 'saucer'), ('soup spoon', 'soup spoon'), ('bundle', 'bundle'), ('eye', 'eye')], max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dietplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DietName', models.CharField(max_length=150)),
                ('info', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=30, null=True)),
                ('age', models.IntegerField(blank=True, default=30, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.fooditem')),
            ],
        ),
    ]
