# Generated by Django 4.2.2 on 2023-07-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='food',
            new_name='fooditem',
        ),
    ]
