# Generated by Django 4.2.2 on 2023-07-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_rename_food_dietplan_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='finalapp.fooditem'),
        ),
    ]
