# Generated by Django 4.2.2 on 2023-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_alter_dietplan_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='fooditem',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='fooditem',
            field=models.ManyToManyField(to='finalapp.fooditem'),
        ),
    ]
